version: '3.3'
services:
  dogs-db:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'dogs'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - dogs-db:/var/lib/mysql
volumes:
  dogs-db:
